[database]
# we're using clickhouse as our database.
# the 5 fields below are creds or details to use to connect to the database.
# use the command below to create a table:

# ```
# CREATE TABLE IF NOT EXISTS server_scans (
#   timestamp DateTime64(3),
#   ip IPv4,
#   port UInt16,
#   response String
# ) ENGINE = MergeTree()
# ORDER BY (ip, port, timestamp);
# ```

# change `server_scans` however you'd like,
# but don't forget to change it in the table field here as well.

url = "REPLACE-ME"
table = "server_scans"

user = ""
password = ""
database = ""

# these fields dictate how cached often found servers should be written.
flush_interval = 30 # if it's been at least N seconds since the last write, write.
flush_capacity = 10 # if we have at least 10 objects cached, write.

[controller]
# the port range which we will scan from
# to prohibit the kernel from closing the connections
# run the following:

# ```
# sudo nft add table inet filter
# sudo nft add chain inet filter output '{ type filter hook output priority 0; policy accept; }'
# sudo nft add rule inet filter output ip protocol tcp tcp flags rst tcp sport <port_range_start>-<port_range_end> drop
# ```

# and to make it persistent, run the following:

# ```
# sudo nft list ruleset | sudo tee /etc/nftables.conf
# sudo systemctl enable --now nftables
# ```
source_port = [42000, 43000]

# the interface that the program will attach to
# commands like "ip addr" or "nmcli d" help find the right interface
# hint: it probably isnt "lo"
interface = "REPLACE-ME"

# per how many seconds the pps info gets printed
print_every = 5

[tcp]
# sometimes tcp packets come to us in a shuffled order.
# this part helps us un-shuffle them while also preventing memory abuse.
# higher = more memory usage but fewer misses
# lower = less memory usage but more misses
max_reorder_segments = 8  # maximum count of shuffled packets we can hold
max_reorder_bytes = 16384 # maximum bytes to hold in cache to un-shuffle when all data is received.

[strategy]
# this should roughly equal to count of packets sent per second,
# but its really how many addresses at a time we keep track of at once
# higher = more memory usage but fewer misses
# lower = less memory usage but more misses
max_rate = 30_000
# probability of exploring, so trying random targets;
# instead of exploiting, so using our knowledge to "guess" targets.
# higher = more packets and more intrusive but fewer misses
# lower = less packets and less intrusive but more misses
epsilon = { ip = 0.05, port = 0.05 }
# how many distinct ports within one ip address will be tried within one session.
# so kind of an intrusiveness control.
# higher = more intrusive, more packets but fewer misses
# lower = less intrusive, fewer packets but more misses
budget_per_address = 100
# ports that might contain server that we want to hint to the scanner
seed_ports = [[25560, 25570]]
# we keep track of ips. however we don't have infinite memory, so we need to clean them up.
# after how much seconds the adapter stops keeping track of the ip.
# higher = more memory usage but slightly better guessing
# lower = less memory usage but slightly worse guessing
timeout = 30
# some ips have the same server on every port (mostly honeypots).
# if we find this many servers with the same byte-for-byte response,
# we'll simply stop looking any further.
catchall_threshold = 5

[session]
# how much each session lasts at max in seconds
duration = 300

rescan = {
    # how many ips at max get queued to be scanned in every rescan session.
    # higher = more memory usage but more diversity of ips
    # lower = less memory usage but less diversity of ips
    max_count = 10_000,
    # probability of rescans occuring each session
    epsilon = 0.005
}

[ping]
# slp payload
host = "farsight"
port = 1337
protocol_version = 47

[xdp]
# use either "copy" or "zero-copy" to force a mode.
# "zero-copy" = fastest, may not be as stable in every driver
# "copy" = fast
# "fallback" = ?, chooses whatever the driver thinks is best
mode = "copy"

# use either "driver", "hardware" or "skb" to force an "attach mode".
# hardware = fastest, usable if the NIC hardware has support for af_xdp
# driver = faster, usable if the NIC driver has support for af_xdp
# skb = fast, basically emulating af_xdp via the kernel. always usable
attach_mode = "skb"

# TCP packets require a checksum for whatever reason, and to compute them is expensive.
# offloading them to the NIC however makes things go fast
# but not every driver may support this with zero-copy simultaneously.
# if you get no throughput with zero-copy, it's probably because of this being true.
# true = fastest, may not be as stable in every driver when coupled with zero-copy
# false = fast
checksum_offload = false

# ring sizes, change only if you know what you're doing.
# higher values may increase memory usage, but it also may improve performance.
ring_size = 2048
